### ISSUE TITLE
编译OpenRoleZoo出错

### ISSUE THREAD

**Issue by yuanzhuohao** [SeetaFace6Open/OpenRoleZoo#2]
在运行`build.linux.x64.sh`报以下的错误

`mkdir: cannot create directory ‘build.linux.x64’: File exists
-- Platform: x64
-- Configuration: Release
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jess/MyLab/index/OpenRoleZoo/craft/build.linux.x64
[  2%] Building CXX object src/CMakeFiles/ORZ_STATIC.dir/orz/mem/vat.cpp.o
[  4%] Building CXX object src/CMakeFiles/ORZ_STATIC.dir/orz/mem/pot.cpp.o
[  7%] Building CXX object src/CMakeFiles/ORZ_STATIC.dir/orz/tools/limit.cpp.o
[  9%] Building CXX object src/CMakeFiles/ORZ_STATIC.dir/orz/tools/fps.cpp.o
[ 12%] Building CXX object src/CMakeFiles/ORZ_STATIC.dir/orz/tools/option.cpp.o
[ 14%] Building CXX object src/CMakeFiles/ORZ_STATIC.dir/orz/tools/resources.cpp.o
[ 17%] Building CXX object src/CMakeFiles/ORZ_STATIC.dir/orz/utils/api.cpp.o
[ 19%] Building CXX object src/CMakeFiles/ORZ_STATIC.dir/orz/tools/progress_bar.cpp.o
[ 21%] Building CXX object src/CMakeFiles/ORZ_STATIC.dir/orz/tools/range.cpp.o
[ 24%] Building CXX object src/CMakeFiles/ORZ_STATIC.dir/orz/utils/except.cpp.o
[ 26%] Building CXX object src/CMakeFiles/ORZ_STATIC.dir/orz/utils/format.cpp.o
[ 29%] Building CXX object src/CMakeFiles/ORZ_STATIC.dir/orz/utils/log.cpp.o
[ 31%] Building CXX object src/CMakeFiles/ORZ_STATIC.dir/orz/utils/platform.cpp.o
[ 34%] Building CXX object src/CMakeFiles/ORZ_STATIC.dir/orz/utils/random.cpp.o
In file included from /home/jess/MyLab/index/OpenRoleZoo/src/orz/mem/pot.cpp:5:
/home/jess/MyLab/index/OpenRoleZoo/src/../include/orz/mem/pot.h:15:32: error: ‘function’ in namespace ‘std’ does not name a template type
   15 |         using allocator = std::function<std::shared_ptr<void>(size_t)>;
      |                                ^~~~~~~~
/home/jess/MyLab/index/OpenRoleZoo/src/../include/orz/mem/pot.h:10:1: note: ‘std::function’ is defined in header ‘<functional>’; did you forget to ‘#include <functional>’?
    9 | #include <memory>
  +++ |+#include <functional>
   10 | 
/home/jess/MyLab/index/OpenRoleZoo/src/../include/orz/mem/pot.h:18:19: error: ‘allocator’ does not name a type; did you mean ‘alloca’?
   18 |         Pot(const allocator &ator);
      |                   ^~~~~~~~~
      |                   alloca
/home/jess/MyLab/index/OpenRoleZoo/src/../include/orz/mem/pot.h:41:9: error: ‘allocator’ does not name a type; did you mean ‘alloca’?
   41 |         allocator m_allocator;
      |         ^~~~~~~~~
      |         alloca
In file included from /home/jess/MyLab/index/OpenRoleZoo/src/../include/orz/mem/vat.h:8,
                 from /home/jess/MyLab/index/OpenRoleZoo/src/orz/mem/vat.cpp:6:
/home/jess/MyLab/index/OpenRoleZoo/src/../include/orz/mem/pot.h:15:32: error: ‘function’ in namespace ‘std’ does not name a template type
   15 |         using allocator = std::function<std::shared_ptr<void>(size_t)>;
      |                                ^~~~~~~~
/home/jess/MyLab/index/OpenRoleZoo/src/orz/mem/pot.cpp: In constructor ‘orz::Pot::Pot()’:
/home/jess/MyLab/index/OpenRoleZoo/src/orz/mem/pot.cpp:17:15: error: invalid conversion from ‘std::shared_ptr<void> (*)(size_t)’ {aka ‘std::shared_ptr<void> (*)(long unsigned int)’} to ‘int’ [-fpermissive]
   17 |         : Pot(default_allocator) {
      |               ^~~~~~~~~~~~~~~~~
      |               |
      |               std::shared_ptr<void> (*)(size_t) {aka std::shared_ptr<void> (*)(long unsigned int)}
In file included from /home/jess/MyLab/index/OpenRoleZoo/src/orz/mem/pot.cpp:5:
/home/jess/MyLab/index/OpenRoleZoo/src/../include/orz/mem/pot.h:18:30: note:   initializing argument 1 of ‘orz::Pot::Pot(const int&)’
   18 |         Pot(const allocator &ator);
      |             ~~~~~~~~~~~~~~~~~^~~~
/home/jess/MyLab/index/OpenRoleZoo/src/orz/mem/pot.cpp: At global scope:
/home/jess/MyLab/index/OpenRoleZoo/src/orz/mem/pot.cpp:20:20: error: ‘allocator’ does not name a type; did you mean ‘alloca’?
   20 |     Pot::Pot(const allocator &ator)
      |                    ^~~~~~~~~
      |                    alloca
/home/jess/MyLab/index/OpenRoleZoo/src/../include/orz/mem/pot.h:10:1: note: ‘std::function’ is defined in header ‘<functional>’; did you forget to ‘#include <functional>’?
    9 | #include <memory>
  +++ |+#include <functional>
   10 | 
/home/jess/MyLab/index/OpenRoleZoo/src/../include/orz/mem/pot.h:18:19: error: ‘allocator’ does not name a type; did you mean ‘alloca’?
   18 |         Pot(const allocator &ator);
      |                   ^~~~~~~~~
      |                   alloca
/home/jess/MyLab/index/OpenRoleZoo/src/orz/mem/pot.cpp: In constructor ‘orz::Pot::Pot(const int&)’:
/home/jess/MyLab/index/OpenRoleZoo/src/orz/mem/pot.cpp:21:12: error: class ‘orz::Pot’ does not have any field named ‘m_allocator’
   21 |         :  m_allocator(ator), m_capacity(0), m_size(0), m_data() {
      |            ^~~~~~~~~~~
/home/jess/MyLab/index/OpenRoleZoo/src/orz/mem/pot.cpp: In member function ‘void* orz::Pot::malloc(size_t)’:
/home/jess/MyLab/index/OpenRoleZoo/src/orz/mem/pot.cpp:26:22: error: ‘m_allocator’ was not declared in this scope
   26 |             m_data = m_allocator(_size);
      |                      ^~~~~~~~~~~
/home/jess/MyLab/index/OpenRoleZoo/src/../include/orz/mem/pot.h:41:9: error: ‘allocator’ does not name a type; did you mean ‘alloca’?
   41 |         allocator m_allocator;
      |         ^~~~~~~~~
      |         alloca
/home/jess/MyLab/index/OpenRoleZoo/src/orz/mem/pot.cpp: In member function ‘void* orz::Pot::relloc(size_t)’:
/home/jess/MyLab/index/OpenRoleZoo/src/orz/mem/pot.cpp:35:29: error: ‘m_allocator’ was not declared in this scope
   35 |             auto new_data = m_allocator(_size);
      |                             ^~~~~~~~~~~
make[2]: *** [src/CMakeFiles/ORZ_STATIC.dir/build.make:297: src/CMakeFiles/ORZ_STATIC.dir/orz/mem/pot.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/jess/MyLab/index/OpenRoleZoo/src/orz/utils/format.cpp: In function ‘std::vector<std::__cxx11::basic_string<char> > orz::Split(const string&, char, size_t)’:
/home/jess/MyLab/index/OpenRoleZoo/src/orz/utils/format.cpp:26:25: warning: moving a local object in a return statement prevents copy elision [-Wpessimizing-move]
   26 |         return std::move(result);
      |                ~~~~~~~~~^~~~~~~~
/home/jess/MyLab/index/OpenRoleZoo/src/orz/utils/format.cpp:26:25: note: remove ‘std::move’ call
/home/jess/MyLab/index/OpenRoleZoo/src/orz/utils/format.cpp: In function ‘std::vector<std::__cxx11::basic_string<char> > orz::Split(const string&, std::string, size_t)’:
/home/jess/MyLab/index/OpenRoleZoo/src/orz/utils/format.cpp:49:25: warning: moving a local object in a return statement prevents copy elision [-Wpessimizing-move]
   49 |         return std::move(result);
      |                ~~~~~~~~~^~~~~~~~
/home/jess/MyLab/index/OpenRoleZoo/src/orz/utils/format.cpp:49:25: note: remove ‘std::move’ call
make[2]: *** [src/CMakeFiles/ORZ_STATIC.dir/build.make:310: src/CMakeFiles/ORZ_STATIC.dir/orz/mem/vat.cpp.o] Error 1
/home/jess/MyLab/index/OpenRoleZoo/src/orz/tools/resources.cpp: In function ‘std::string orz::resources::to_var(const string&)’:
/home/jess/MyLab/index/OpenRoleZoo/src/orz/tools/resources.cpp:369:29: warning: moving a local object in a return statement prevents copy elision [-Wpessimizing-move]
  369 |             return std::move(local_var);
      |                    ~~~~~~~~~^~~~~~~~~~~
/home/jess/MyLab/index/OpenRoleZoo/src/orz/tools/resources.cpp:369:29: note: remove ‘std::move’ call
make[1]: *** [CMakeFiles/Makefile2:123: src/CMakeFiles/ORZ_STATIC.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
[  2%] Building CXX object src/CMakeFiles/ORZ_STATIC.dir/orz/mem/pot.cpp.o
In file included from /home/jess/MyLab/index/OpenRoleZoo/src/orz/mem/pot.cpp:5:
/home/jess/MyLab/index/OpenRoleZoo/src/../include/orz/mem/pot.h:15:32: error: ‘function’ in namespace ‘std’ does not name a template type
   15 |         using allocator = std::function<std::shared_ptr<void>(size_t)>;
      |                                ^~~~~~~~
/home/jess/MyLab/index/OpenRoleZoo/src/../include/orz/mem/pot.h:10:1: note: ‘std::function’ is defined in header ‘<functional>’; did you forget to ‘#include <functional>’?
    9 | #include <memory>
  +++ |+#include <functional>
   10 | 
/home/jess/MyLab/index/OpenRoleZoo/src/../include/orz/mem/pot.h:18:19: error: ‘allocator’ does not name a type; did you mean ‘alloca’?
   18 |         Pot(const allocator &ator);
      |                   ^~~~~~~~~
      |                   alloca
/home/jess/MyLab/index/OpenRoleZoo/src/../include/orz/mem/pot.h:41:9: error: ‘allocator’ does not name a type; did you mean ‘alloca’?
   41 |         allocator m_allocator;
      |         ^~~~~~~~~
      |         alloca
/home/jess/MyLab/index/OpenRoleZoo/src/orz/mem/pot.cpp: In constructor ‘orz::Pot::Pot()’:
/home/jess/MyLab/index/OpenRoleZoo/src/orz/mem/pot.cpp:17:15: error: invalid conversion from ‘std::shared_ptr<void> (*)(size_t)’ {aka ‘std::shared_ptr<void> (*)(long unsigned int)’} to ‘int’ [-fpermissive]
   17 |         : Pot(default_allocator) {
      |               ^~~~~~~~~~~~~~~~~
      |               |
      |               std::shared_ptr<void> (*)(size_t) {aka std::shared_ptr<void> (*)(long unsigned int)}
In file included from /home/jess/MyLab/index/OpenRoleZoo/src/orz/mem/pot.cpp:5:
/home/jess/MyLab/index/OpenRoleZoo/src/../include/orz/mem/pot.h:18:30: note:   initializing argument 1 of ‘orz::Pot::Pot(const int&)’
   18 |         Pot(const allocator &ator);
      |             ~~~~~~~~~~~~~~~~~^~~~
/home/jess/MyLab/index/OpenRoleZoo/src/orz/mem/pot.cpp: At global scope:
/home/jess/MyLab/index/OpenRoleZoo/src/orz/mem/pot.cpp:20:20: error: ‘allocator’ does not name a type; did you mean ‘alloca’?
   20 |     Pot::Pot(const allocator &ator)
      |                    ^~~~~~~~~
      |                    alloca
/home/jess/MyLab/index/OpenRoleZoo/src/orz/mem/pot.cpp: In constructor ‘orz::Pot::Pot(const int&)’:
/home/jess/MyLab/index/OpenRoleZoo/src/orz/mem/pot.cpp:21:12: error: class ‘orz::Pot’ does not have any field named ‘m_allocator’
   21 |         :  m_allocator(ator), m_capacity(0), m_size(0), m_data() {
      |            ^~~~~~~~~~~
/home/jess/MyLab/index/OpenRoleZoo/src/orz/mem/pot.cpp: In member function ‘void* orz::Pot::malloc(size_t)’:
/home/jess/MyLab/index/OpenRoleZoo/src/orz/mem/pot.cpp:26:22: error: ‘m_allocator’ was not declared in this scope
   26 |             m_data = m_allocator(_size);
      |                      ^~~~~~~~~~~
/home/jess/MyLab/index/OpenRoleZoo/src/orz/mem/pot.cpp: In member function ‘void* orz::Pot::relloc(size_t)’:
/home/jess/MyLab/index/OpenRoleZoo/src/orz/mem/pot.cpp:35:29: error: ‘m_allocator’ was not declared in this scope
   35 |             auto new_data = m_allocator(_size);
      |                             ^~~~~~~~~~~
make[2]: *** [src/CMakeFiles/ORZ_STATIC.dir/build.make:297: src/CMakeFiles/ORZ_STATIC.dir/orz/mem/pot.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:123: src/CMakeFiles/ORZ_STATIC.dir/all] Error 2
make: *** [Makefile:130: all] Error 2`

**Comment by yuanzhuohao** [comment]
在`pot.h`头文件添加`#include <functional>`解决了。

**Comment by h3clikejava** [comment]
大牛啊，膜拜，搞半天。终于按照您的方法弄好了。跪拜
